### PR TITLE
31 add annual protocol rmd

### PR DESCRIPTION
**Pull request by mrdufour**
Closes issue #31

### CODE REVIEW

**Review by gfs8966 — APPROVED** [review]
Template rmd is created on project set up as expected.

**Comment by mrdufour** [comment]
Closed issue #31

**Comment by HoldenJe** [comment]
@mrdufour can #33 (31-add-annual-protocol) be deleted now?

**Comment by mrdufour** [comment]
Yep, I think so. I'm liking the workflow, now that I'm getting the hand of it.

I'll delete that branch.

**Pull request merged**
