### PR TITLE
Development

### PR DESCRIPTION
**Pull request by mrdufour**
Added export image code to the export function. Took me a bit to figure out that the V in EVFile should be capitalized! Seems to be working well now.

### CODE REVIEW

**Comment by gfs8966** [comment]
@mrdufour I might be able to review these changes but not sure if I'll be able to test them in the short term. Can you manage running the development build in the interim? I'll test and review (and fix the merge conflict) before merging to main.

**Comment by mrdufour** [comment]
Yep, I ran on my end and everything checks out. Requires template with editable BottomExclusion and SurfaceExclusion lines built in. I'll send it over.

**Review by mrdufour — COMMENTED** [review]
I've tested this on the CB data - working as intended

**Review by mrdufour — COMMENTED** [review]
Tested on CB data - mostly working well - need to add line of code that specifically assigns region type as 'Analysis'

**Comment by HoldenJe** [comment]
@mrdufour the editable bottom and surface lines are good additions but we need to manage downstream functions. The export script as written will reset the analysis lines to the virtual lines. We can either modify the export function or change the name of the editable lines removing the "_editable". Pros and cons to either approach but wanted to flag it before you ran exports.

**Pull request merged**
